USE webtorkel;
INSERT INTO combat_texts (combat_id, text) VALUES (0, 'GAME OVER');
INSERT INTO combat_texts (combat_id, text) VALUES (1, 'Torkel upptäcker att han aldrig har funnits.');
INSERT INTO combat_texts (combat_id, text) VALUES (2, 'Torkel vaknar upp ur mardrömmen.');
INSERT INTO combat_texts (combat_id, text) VALUES (3, 'Torkel blir mirakulöst räddad.');
INSERT INTO combat_texts (combat_id, text) VALUES (4, 'Torkel har upphört att existera.');
INSERT INTO combat_texts (combat_id, text) VALUES (5, 'Torkel finns ej mera.');
INSERT INTO combat_texts (combat_id, text) VALUES (6, 'Torkel lägger benen på ryggen.');
INSERT INTO combat_texts (combat_id, text) VALUES (7, 'Torkel möter hjältedöden.');
INSERT INTO combat_texts (combat_id, text) VALUES (8, 'Torkel blir tillfångatagen.');
INSERT INTO combat_texts (combat_id, text) VALUES (9, 'Torkel dödar en av motståndarna, fortsätter slåss.');
INSERT INTO combat_texts (combat_id, text) VALUES (10, 'Fienden får in en lyckoträff.');
INSERT INTO combat_texts (combat_id, text) VALUES (11, 'Torkel blir skadad.');
INSERT INTO combat_texts (combat_id, text) VALUES (12, 'Torkel gör processen kort.');
INSERT INTO combat_texts (combat_id, text) VALUES (13, 'Torkel klantar till det.');
INSERT INTO combat_texts (combat_id, text) VALUES (14, 'Torkel hugger ner fienden.');
INSERT INTO combat_texts (combat_id, text) VALUES (15, 'Fienden ger sig.');
INSERT INTO combat_texts (combat_id, text) VALUES (16, 'Fienden flyr.');
INSERT INTO combat_texts (combat_id, text) VALUES (17, 'Torkel massakrerar fienden.');
INSERT INTO combat_texts (combat_id, text) VALUES (18, 'Torkel gör köttfärs av fienden.');
INSERT INTO combat_texts (combat_id, text) VALUES (19, 'Fienden säger: "Jag är inte riktigt död än.".');
INSERT INTO combat_texts (combat_id, text) VALUES (20, 'För dåligt motstånd.');
